// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugefzrktqeyspnzhxzzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZWZ6cmt0cWV5c3Buemh4enp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNTI2NTIsImV4cCI6MjA3MTcyODY1Mn0.vVGtBuwYN1tSviYCLxbZpUnl7S6peZrtLAhyd7BnxVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});